name: CI/CD Pipeline to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: 'Build and Push Docker Image'
      run: |
        docker build . -t ${{ secrets.AZURE_REGISTRY_SERVER }}/mi-app-medica:${{ github.sha }}
        docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/mi-app-medica:${{ github.sha }}
